// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: fence_module.proto

package v1alpha1

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Fence struct {
	// service ports enable lazyload
	WormholePort []string `protobuf:"bytes,1,rep,name=wormholePort,proto3" json:"wormholePort,omitempty"`
	// whether enable ServiceFence auto generating
	// default value is false
	DisableAutoFence bool `protobuf:"varint,2,opt,name=disableAutoFence,proto3" json:"disableAutoFence,omitempty"`
	// the namespace list which enable lazyload
	Namespace []string `protobuf:"bytes,3,rep,name=namespace,proto3" json:"namespace,omitempty"`
	// custom outside dispatch traffic rules
	Dispatches []*Dispatch `protobuf:"bytes,4,rep,name=dispatches,proto3" json:"dispatches,omitempty"`
	// can convert to one or many domain alias rules
	DomainAliases        []*DomainAlias `protobuf:"bytes,5,rep,name=domainAliases,proto3" json:"domainAliases,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Fence) Reset()         { *m = Fence{} }
func (m *Fence) String() string { return proto.CompactTextString(m) }
func (*Fence) ProtoMessage()    {}
func (*Fence) Descriptor() ([]byte, []int) {
	return fileDescriptor_8eebc4b237a55c9b, []int{0}
}
func (m *Fence) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Fence.Unmarshal(m, b)
}
func (m *Fence) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Fence.Marshal(b, m, deterministic)
}
func (m *Fence) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Fence.Merge(m, src)
}
func (m *Fence) XXX_Size() int {
	return xxx_messageInfo_Fence.Size(m)
}
func (m *Fence) XXX_DiscardUnknown() {
	xxx_messageInfo_Fence.DiscardUnknown(m)
}

var xxx_messageInfo_Fence proto.InternalMessageInfo

func (m *Fence) GetWormholePort() []string {
	if m != nil {
		return m.WormholePort
	}
	return nil
}

func (m *Fence) GetDisableAutoFence() bool {
	if m != nil {
		return m.DisableAutoFence
	}
	return false
}

func (m *Fence) GetNamespace() []string {
	if m != nil {
		return m.Namespace
	}
	return nil
}

func (m *Fence) GetDispatches() []*Dispatch {
	if m != nil {
		return m.Dispatches
	}
	return nil
}

func (m *Fence) GetDomainAliases() []*DomainAlias {
	if m != nil {
		return m.DomainAliases
	}
	return nil
}

// The general idea is to assign different default traffic to different targets
// for correct processing by means of domain matching.
type Dispatch struct {
	// dispatch rule name
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// domain matching contents
	Domains []string `protobuf:"bytes,2,rep,name=domains,proto3" json:"domains,omitempty"`
	// target cluster
	Cluster              string   `protobuf:"bytes,3,opt,name=cluster,proto3" json:"cluster,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Dispatch) Reset()         { *m = Dispatch{} }
func (m *Dispatch) String() string { return proto.CompactTextString(m) }
func (*Dispatch) ProtoMessage()    {}
func (*Dispatch) Descriptor() ([]byte, []int) {
	return fileDescriptor_8eebc4b237a55c9b, []int{1}
}
func (m *Dispatch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Dispatch.Unmarshal(m, b)
}
func (m *Dispatch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Dispatch.Marshal(b, m, deterministic)
}
func (m *Dispatch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Dispatch.Merge(m, src)
}
func (m *Dispatch) XXX_Size() int {
	return xxx_messageInfo_Dispatch.Size(m)
}
func (m *Dispatch) XXX_DiscardUnknown() {
	xxx_messageInfo_Dispatch.DiscardUnknown(m)
}

var xxx_messageInfo_Dispatch proto.InternalMessageInfo

func (m *Dispatch) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Dispatch) GetDomains() []string {
	if m != nil {
		return m.Domains
	}
	return nil
}

func (m *Dispatch) GetCluster() string {
	if m != nil {
		return m.Cluster
	}
	return ""
}

// DomainAlias regexp expression, which is alias for target domain
// default value is empty
// example:
// domainAliases:
//   - pattern: (?P<service>[^\.]+)\.(?P<namespace>[^\.]+)\.svc\.cluster\.local$
//     template:
//       - $namespace.$service.service.mailsaas
type DomainAlias struct {
	Pattern              string   `protobuf:"bytes,1,opt,name=pattern,proto3" json:"pattern,omitempty"`
	Templates            []string `protobuf:"bytes,2,rep,name=templates,proto3" json:"templates,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DomainAlias) Reset()         { *m = DomainAlias{} }
func (m *DomainAlias) String() string { return proto.CompactTextString(m) }
func (*DomainAlias) ProtoMessage()    {}
func (*DomainAlias) Descriptor() ([]byte, []int) {
	return fileDescriptor_8eebc4b237a55c9b, []int{2}
}
func (m *DomainAlias) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DomainAlias.Unmarshal(m, b)
}
func (m *DomainAlias) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DomainAlias.Marshal(b, m, deterministic)
}
func (m *DomainAlias) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DomainAlias.Merge(m, src)
}
func (m *DomainAlias) XXX_Size() int {
	return xxx_messageInfo_DomainAlias.Size(m)
}
func (m *DomainAlias) XXX_DiscardUnknown() {
	xxx_messageInfo_DomainAlias.DiscardUnknown(m)
}

var xxx_messageInfo_DomainAlias proto.InternalMessageInfo

func (m *DomainAlias) GetPattern() string {
	if m != nil {
		return m.Pattern
	}
	return ""
}

func (m *DomainAlias) GetTemplates() []string {
	if m != nil {
		return m.Templates
	}
	return nil
}

func init() {
	proto.RegisterType((*Fence)(nil), "slime.microservice.lazyload.v1alpha1.Fence")
	proto.RegisterType((*Dispatch)(nil), "slime.microservice.lazyload.v1alpha1.Dispatch")
	proto.RegisterType((*DomainAlias)(nil), "slime.microservice.lazyload.v1alpha1.DomainAlias")
}

func init() { proto.RegisterFile("fence_module.proto", fileDescriptor_8eebc4b237a55c9b) }

var fileDescriptor_8eebc4b237a55c9b = []byte{
	// 313 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xc1, 0x4a, 0x3b, 0x31,
	0x10, 0xc6, 0xd9, 0x6e, 0xfb, 0xff, 0xb7, 0xa9, 0x82, 0xe4, 0x94, 0x83, 0x87, 0x65, 0xf1, 0xb0,
	0x88, 0x64, 0xa9, 0x3e, 0x41, 0x45, 0x3d, 0x8a, 0xec, 0x45, 0xf0, 0x22, 0xd3, 0xec, 0x48, 0x03,
	0xc9, 0x26, 0x24, 0x69, 0x45, 0x1f, 0xc6, 0x67, 0x95, 0x4d, 0x1b, 0xb6, 0xc5, 0x4b, 0x6f, 0x33,
	0x5f, 0xf2, 0xfd, 0x26, 0x5f, 0x18, 0x42, 0x3f, 0xb0, 0x13, 0xf8, 0xae, 0x4d, 0xbb, 0x51, 0xc8,
	0xad, 0x33, 0xc1, 0xd0, 0x2b, 0xaf, 0xa4, 0x46, 0xae, 0xa5, 0x70, 0xc6, 0xa3, 0xdb, 0x4a, 0x81,
	0x5c, 0xc1, 0xf7, 0x97, 0x32, 0xd0, 0xf2, 0xed, 0x02, 0x94, 0x5d, 0xc3, 0xa2, 0xfc, 0x19, 0x91,
	0xc9, 0x53, 0x6f, 0xa6, 0x25, 0x39, 0xfb, 0x34, 0x4e, 0xaf, 0x8d, 0xc2, 0x17, 0xe3, 0x02, 0xcb,
	0x8a, 0xbc, 0x9a, 0x35, 0x47, 0x1a, 0xbd, 0x26, 0x17, 0xad, 0xf4, 0xb0, 0x52, 0xb8, 0xdc, 0x04,
	0x13, 0x7d, 0x6c, 0x54, 0x64, 0xd5, 0xb4, 0xf9, 0xa3, 0xd3, 0x4b, 0x32, 0xeb, 0x40, 0xa3, 0xb7,
	0x20, 0x90, 0xe5, 0x11, 0x36, 0x08, 0xf4, 0x99, 0x90, 0x56, 0x7a, 0x0b, 0x41, 0xac, 0xd1, 0xb3,
	0x71, 0x91, 0x57, 0xf3, 0x5b, 0xce, 0x4f, 0x79, 0x32, 0x7f, 0xd8, 0xfb, 0x9a, 0x03, 0x02, 0x7d,
	0x25, 0xe7, 0xad, 0xd1, 0x20, 0xbb, 0xa5, 0x92, 0xe0, 0xd1, 0xb3, 0x49, 0x44, 0x2e, 0x4e, 0x44,
	0x0e, 0xd6, 0xe6, 0x98, 0x53, 0x36, 0x64, 0x9a, 0x06, 0x52, 0x4a, 0xc6, 0x7d, 0x02, 0x96, 0x15,
	0x59, 0x35, 0x6b, 0x62, 0x4d, 0x19, 0xf9, 0xbf, 0x33, 0x78, 0x36, 0x8a, 0x21, 0x53, 0xdb, 0x9f,
	0x08, 0xb5, 0xf1, 0x01, 0x1d, 0xcb, 0xa3, 0x21, 0xb5, 0xe5, 0x23, 0x99, 0x1f, 0x4c, 0xec, 0x2f,
	0x5a, 0x08, 0x01, 0x5d, 0xb7, 0x27, 0xa7, 0xb6, 0xff, 0xc3, 0x80, 0xda, 0x2a, 0x08, 0x98, 0xf0,
	0x83, 0x70, 0xcf, 0xdf, 0x6e, 0x76, 0xe9, 0xa4, 0xa9, 0x63, 0x51, 0xef, 0x16, 0xc0, 0xd7, 0x29,
	0x61, 0x0d, 0x56, 0xd6, 0x29, 0xe5, 0xea, 0x5f, 0x5c, 0x8c, 0xbb, 0xdf, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x70, 0x6e, 0xcc, 0x00, 0x2e, 0x02, 0x00, 0x00,
}
