// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: service_fence.proto

package v1alpha1

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Destinations_Status int32

const (
	Destinations_ACTIVE Destinations_Status = 0
	Destinations_EXPIRE Destinations_Status = 1
)

var Destinations_Status_name = map[int32]string{
	0: "ACTIVE",
	1: "EXPIRE",
}

var Destinations_Status_value = map[string]int32{
	"ACTIVE": 0,
	"EXPIRE": 1,
}

func (x Destinations_Status) String() string {
	return proto.EnumName(Destinations_Status_name, int32(x))
}

func (Destinations_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b4b8d9f0db3c7310, []int{3, 0}
}

type Timestamp struct {
	// Represents seconds of UTC time since Unix epoch
	// 1970-01-01T00:00:00Z. Must be from 0001-01-01T00:00:00Z to
	// 9999-12-31T23:59:59Z inclusive.
	Seconds int64 `protobuf:"varint,1,opt,name=seconds,proto3" json:"seconds,omitempty"`
	// Non-negative fractions of a second at nanosecond resolution. Negative
	// second values with fractions must still have non-negative nanos values
	// that count forward in time. Must be from 0 to 999,999,999
	// inclusive.
	Nanos                int32    `protobuf:"varint,2,opt,name=nanos,proto3" json:"nanos,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Timestamp) Reset()         { *m = Timestamp{} }
func (m *Timestamp) String() string { return proto.CompactTextString(m) }
func (*Timestamp) ProtoMessage()    {}
func (*Timestamp) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4b8d9f0db3c7310, []int{0}
}
func (m *Timestamp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Timestamp.Unmarshal(m, b)
}
func (m *Timestamp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Timestamp.Marshal(b, m, deterministic)
}
func (m *Timestamp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Timestamp.Merge(m, src)
}
func (m *Timestamp) XXX_Size() int {
	return xxx_messageInfo_Timestamp.Size(m)
}
func (m *Timestamp) XXX_DiscardUnknown() {
	xxx_messageInfo_Timestamp.DiscardUnknown(m)
}

var xxx_messageInfo_Timestamp proto.InternalMessageInfo

func (m *Timestamp) GetSeconds() int64 {
	if m != nil {
		return m.Seconds
	}
	return 0
}

func (m *Timestamp) GetNanos() int32 {
	if m != nil {
		return m.Nanos
	}
	return 0
}

type ServiceFenceSpec struct {
	Host map[string]*RecyclingStrategy `protobuf:"bytes,1,rep,name=host,proto3" json:"host,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Switch to render servicefence as sidecar
	Enable               bool     `protobuf:"varint,2,opt,name=enable,proto3" json:"enable,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceFenceSpec) Reset()         { *m = ServiceFenceSpec{} }
func (m *ServiceFenceSpec) String() string { return proto.CompactTextString(m) }
func (*ServiceFenceSpec) ProtoMessage()    {}
func (*ServiceFenceSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4b8d9f0db3c7310, []int{1}
}
func (m *ServiceFenceSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceFenceSpec.Unmarshal(m, b)
}
func (m *ServiceFenceSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceFenceSpec.Marshal(b, m, deterministic)
}
func (m *ServiceFenceSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceFenceSpec.Merge(m, src)
}
func (m *ServiceFenceSpec) XXX_Size() int {
	return xxx_messageInfo_ServiceFenceSpec.Size(m)
}
func (m *ServiceFenceSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceFenceSpec.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceFenceSpec proto.InternalMessageInfo

func (m *ServiceFenceSpec) GetHost() map[string]*RecyclingStrategy {
	if m != nil {
		return m.Host
	}
	return nil
}

func (m *ServiceFenceSpec) GetEnable() bool {
	if m != nil {
		return m.Enable
	}
	return false
}

type RecyclingStrategy struct {
	// Configuration that will not be cleaned up
	Stable *RecyclingStrategy_Stable `protobuf:"bytes,1,opt,name=stable,proto3" json:"stable,omitempty"`
	// Configurations that expire after expiration
	Deadline *RecyclingStrategy_Deadline `protobuf:"bytes,2,opt,name=deadline,proto3" json:"deadline,omitempty"`
	// Deprecated
	Auto                 *RecyclingStrategy_Auto `protobuf:"bytes,3,opt,name=auto,proto3" json:"auto,omitempty"`
	RecentlyCalled       *Timestamp              `protobuf:"bytes,4,opt,name=RecentlyCalled,proto3" json:"RecentlyCalled,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *RecyclingStrategy) Reset()         { *m = RecyclingStrategy{} }
func (m *RecyclingStrategy) String() string { return proto.CompactTextString(m) }
func (*RecyclingStrategy) ProtoMessage()    {}
func (*RecyclingStrategy) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4b8d9f0db3c7310, []int{2}
}
func (m *RecyclingStrategy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecyclingStrategy.Unmarshal(m, b)
}
func (m *RecyclingStrategy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecyclingStrategy.Marshal(b, m, deterministic)
}
func (m *RecyclingStrategy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecyclingStrategy.Merge(m, src)
}
func (m *RecyclingStrategy) XXX_Size() int {
	return xxx_messageInfo_RecyclingStrategy.Size(m)
}
func (m *RecyclingStrategy) XXX_DiscardUnknown() {
	xxx_messageInfo_RecyclingStrategy.DiscardUnknown(m)
}

var xxx_messageInfo_RecyclingStrategy proto.InternalMessageInfo

func (m *RecyclingStrategy) GetStable() *RecyclingStrategy_Stable {
	if m != nil {
		return m.Stable
	}
	return nil
}

func (m *RecyclingStrategy) GetDeadline() *RecyclingStrategy_Deadline {
	if m != nil {
		return m.Deadline
	}
	return nil
}

func (m *RecyclingStrategy) GetAuto() *RecyclingStrategy_Auto {
	if m != nil {
		return m.Auto
	}
	return nil
}

func (m *RecyclingStrategy) GetRecentlyCalled() *Timestamp {
	if m != nil {
		return m.RecentlyCalled
	}
	return nil
}

type RecyclingStrategy_Stable struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecyclingStrategy_Stable) Reset()         { *m = RecyclingStrategy_Stable{} }
func (m *RecyclingStrategy_Stable) String() string { return proto.CompactTextString(m) }
func (*RecyclingStrategy_Stable) ProtoMessage()    {}
func (*RecyclingStrategy_Stable) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4b8d9f0db3c7310, []int{2, 0}
}
func (m *RecyclingStrategy_Stable) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecyclingStrategy_Stable.Unmarshal(m, b)
}
func (m *RecyclingStrategy_Stable) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecyclingStrategy_Stable.Marshal(b, m, deterministic)
}
func (m *RecyclingStrategy_Stable) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecyclingStrategy_Stable.Merge(m, src)
}
func (m *RecyclingStrategy_Stable) XXX_Size() int {
	return xxx_messageInfo_RecyclingStrategy_Stable.Size(m)
}
func (m *RecyclingStrategy_Stable) XXX_DiscardUnknown() {
	xxx_messageInfo_RecyclingStrategy_Stable.DiscardUnknown(m)
}

var xxx_messageInfo_RecyclingStrategy_Stable proto.InternalMessageInfo

type RecyclingStrategy_Deadline struct {
	Expire               *Timestamp `protobuf:"bytes,1,opt,name=expire,proto3" json:"expire,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *RecyclingStrategy_Deadline) Reset()         { *m = RecyclingStrategy_Deadline{} }
func (m *RecyclingStrategy_Deadline) String() string { return proto.CompactTextString(m) }
func (*RecyclingStrategy_Deadline) ProtoMessage()    {}
func (*RecyclingStrategy_Deadline) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4b8d9f0db3c7310, []int{2, 1}
}
func (m *RecyclingStrategy_Deadline) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecyclingStrategy_Deadline.Unmarshal(m, b)
}
func (m *RecyclingStrategy_Deadline) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecyclingStrategy_Deadline.Marshal(b, m, deterministic)
}
func (m *RecyclingStrategy_Deadline) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecyclingStrategy_Deadline.Merge(m, src)
}
func (m *RecyclingStrategy_Deadline) XXX_Size() int {
	return xxx_messageInfo_RecyclingStrategy_Deadline.Size(m)
}
func (m *RecyclingStrategy_Deadline) XXX_DiscardUnknown() {
	xxx_messageInfo_RecyclingStrategy_Deadline.DiscardUnknown(m)
}

var xxx_messageInfo_RecyclingStrategy_Deadline proto.InternalMessageInfo

func (m *RecyclingStrategy_Deadline) GetExpire() *Timestamp {
	if m != nil {
		return m.Expire
	}
	return nil
}

type RecyclingStrategy_Auto struct {
	Duration             *Timestamp `protobuf:"bytes,1,opt,name=duration,proto3" json:"duration,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *RecyclingStrategy_Auto) Reset()         { *m = RecyclingStrategy_Auto{} }
func (m *RecyclingStrategy_Auto) String() string { return proto.CompactTextString(m) }
func (*RecyclingStrategy_Auto) ProtoMessage()    {}
func (*RecyclingStrategy_Auto) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4b8d9f0db3c7310, []int{2, 2}
}
func (m *RecyclingStrategy_Auto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecyclingStrategy_Auto.Unmarshal(m, b)
}
func (m *RecyclingStrategy_Auto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecyclingStrategy_Auto.Marshal(b, m, deterministic)
}
func (m *RecyclingStrategy_Auto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecyclingStrategy_Auto.Merge(m, src)
}
func (m *RecyclingStrategy_Auto) XXX_Size() int {
	return xxx_messageInfo_RecyclingStrategy_Auto.Size(m)
}
func (m *RecyclingStrategy_Auto) XXX_DiscardUnknown() {
	xxx_messageInfo_RecyclingStrategy_Auto.DiscardUnknown(m)
}

var xxx_messageInfo_RecyclingStrategy_Auto proto.InternalMessageInfo

func (m *RecyclingStrategy_Auto) GetDuration() *Timestamp {
	if m != nil {
		return m.Duration
	}
	return nil
}

type Destinations struct {
	// Deprecated
	RecentlyCalled       *Timestamp          `protobuf:"bytes,1,opt,name=RecentlyCalled,proto3" json:"RecentlyCalled,omitempty"`
	Hosts                []string            `protobuf:"bytes,2,rep,name=hosts,proto3" json:"hosts,omitempty"`
	Status               Destinations_Status `protobuf:"varint,3,opt,name=status,proto3,enum=slime.microservice.lazyload.v1alpha1.Destinations_Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Destinations) Reset()         { *m = Destinations{} }
func (m *Destinations) String() string { return proto.CompactTextString(m) }
func (*Destinations) ProtoMessage()    {}
func (*Destinations) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4b8d9f0db3c7310, []int{3}
}
func (m *Destinations) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Destinations.Unmarshal(m, b)
}
func (m *Destinations) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Destinations.Marshal(b, m, deterministic)
}
func (m *Destinations) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Destinations.Merge(m, src)
}
func (m *Destinations) XXX_Size() int {
	return xxx_messageInfo_Destinations.Size(m)
}
func (m *Destinations) XXX_DiscardUnknown() {
	xxx_messageInfo_Destinations.DiscardUnknown(m)
}

var xxx_messageInfo_Destinations proto.InternalMessageInfo

func (m *Destinations) GetRecentlyCalled() *Timestamp {
	if m != nil {
		return m.RecentlyCalled
	}
	return nil
}

func (m *Destinations) GetHosts() []string {
	if m != nil {
		return m.Hosts
	}
	return nil
}

func (m *Destinations) GetStatus() Destinations_Status {
	if m != nil {
		return m.Status
	}
	return Destinations_ACTIVE
}

type ServiceFenceStatus struct {
	Domains              map[string]*Destinations `protobuf:"bytes,1,rep,name=domains,proto3" json:"domains,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	MetricStatus         map[string]string        `protobuf:"bytes,3,rep,name=metricStatus,proto3" json:"metricStatus,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Visitor              map[string]bool          `protobuf:"bytes,2,rep,name=visitor,proto3" json:"visitor,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *ServiceFenceStatus) Reset()         { *m = ServiceFenceStatus{} }
func (m *ServiceFenceStatus) String() string { return proto.CompactTextString(m) }
func (*ServiceFenceStatus) ProtoMessage()    {}
func (*ServiceFenceStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4b8d9f0db3c7310, []int{4}
}
func (m *ServiceFenceStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceFenceStatus.Unmarshal(m, b)
}
func (m *ServiceFenceStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceFenceStatus.Marshal(b, m, deterministic)
}
func (m *ServiceFenceStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceFenceStatus.Merge(m, src)
}
func (m *ServiceFenceStatus) XXX_Size() int {
	return xxx_messageInfo_ServiceFenceStatus.Size(m)
}
func (m *ServiceFenceStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceFenceStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceFenceStatus proto.InternalMessageInfo

func (m *ServiceFenceStatus) GetDomains() map[string]*Destinations {
	if m != nil {
		return m.Domains
	}
	return nil
}

func (m *ServiceFenceStatus) GetMetricStatus() map[string]string {
	if m != nil {
		return m.MetricStatus
	}
	return nil
}

func (m *ServiceFenceStatus) GetVisitor() map[string]bool {
	if m != nil {
		return m.Visitor
	}
	return nil
}

func init() {
	proto.RegisterEnum("slime.microservice.lazyload.v1alpha1.Destinations_Status", Destinations_Status_name, Destinations_Status_value)
	proto.RegisterType((*Timestamp)(nil), "slime.microservice.lazyload.v1alpha1.Timestamp")
	proto.RegisterType((*ServiceFenceSpec)(nil), "slime.microservice.lazyload.v1alpha1.ServiceFenceSpec")
	proto.RegisterMapType((map[string]*RecyclingStrategy)(nil), "slime.microservice.lazyload.v1alpha1.ServiceFenceSpec.HostEntry")
	proto.RegisterType((*RecyclingStrategy)(nil), "slime.microservice.lazyload.v1alpha1.RecyclingStrategy")
	proto.RegisterType((*RecyclingStrategy_Stable)(nil), "slime.microservice.lazyload.v1alpha1.RecyclingStrategy.Stable")
	proto.RegisterType((*RecyclingStrategy_Deadline)(nil), "slime.microservice.lazyload.v1alpha1.RecyclingStrategy.Deadline")
	proto.RegisterType((*RecyclingStrategy_Auto)(nil), "slime.microservice.lazyload.v1alpha1.RecyclingStrategy.Auto")
	proto.RegisterType((*Destinations)(nil), "slime.microservice.lazyload.v1alpha1.Destinations")
	proto.RegisterType((*ServiceFenceStatus)(nil), "slime.microservice.lazyload.v1alpha1.ServiceFenceStatus")
	proto.RegisterMapType((map[string]*Destinations)(nil), "slime.microservice.lazyload.v1alpha1.ServiceFenceStatus.DomainsEntry")
	proto.RegisterMapType((map[string]string)(nil), "slime.microservice.lazyload.v1alpha1.ServiceFenceStatus.MetricStatusEntry")
	proto.RegisterMapType((map[string]bool)(nil), "slime.microservice.lazyload.v1alpha1.ServiceFenceStatus.VisitorEntry")
}

func init() { proto.RegisterFile("service_fence.proto", fileDescriptor_b4b8d9f0db3c7310) }

var fileDescriptor_b4b8d9f0db3c7310 = []byte{
	// 609 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x95, 0x41, 0x6f, 0xd3, 0x30,
	0x14, 0xc7, 0xc9, 0xda, 0x75, 0xed, 0x5b, 0x35, 0x75, 0x66, 0x42, 0x55, 0x4f, 0x55, 0xc5, 0xa1,
	0x07, 0x94, 0x68, 0xe5, 0x00, 0x0c, 0x04, 0x1b, 0x5b, 0x61, 0x03, 0x4d, 0x1a, 0xce, 0x34, 0x10,
	0x42, 0x9a, 0xbc, 0xc4, 0x6c, 0x16, 0x8e, 0x1d, 0xc5, 0x4e, 0x45, 0xf8, 0x44, 0xdc, 0xf9, 0x66,
	0x7c, 0x02, 0x14, 0x3b, 0xa9, 0xb2, 0xad, 0x12, 0x5d, 0xe0, 0xe6, 0xa7, 0xd8, 0xbf, 0xff, 0xfb,
	0x3f, 0xfb, 0xbd, 0xc0, 0x7d, 0x45, 0x93, 0x19, 0x0b, 0xe8, 0xf9, 0x57, 0x2a, 0x02, 0xea, 0xc6,
	0x89, 0xd4, 0x12, 0x3d, 0x54, 0x9c, 0x45, 0xd4, 0x8d, 0x58, 0x90, 0xc8, 0xe2, 0xbb, 0xcb, 0xc9,
	0x8f, 0x8c, 0x4b, 0x12, 0xba, 0xb3, 0x6d, 0xc2, 0xe3, 0x2b, 0xb2, 0x3d, 0x7a, 0x0e, 0x9d, 0x53,
	0x16, 0x51, 0xa5, 0x49, 0x14, 0xa3, 0x3e, 0xac, 0x29, 0x1a, 0x48, 0x11, 0xaa, 0xbe, 0x33, 0x74,
	0xc6, 0x0d, 0x5c, 0x86, 0x68, 0x0b, 0x56, 0x05, 0x11, 0x52, 0xf5, 0x57, 0x86, 0xce, 0x78, 0x15,
	0xdb, 0x60, 0xf4, 0xdb, 0x81, 0x9e, 0x6f, 0xd1, 0x6f, 0x72, 0x65, 0x3f, 0xa6, 0x01, 0x3a, 0x85,
	0xe6, 0x95, 0x54, 0xba, 0xef, 0x0c, 0x1b, 0xe3, 0xf5, 0xc9, 0xae, 0xbb, 0x4c, 0x1a, 0xee, 0x4d,
	0x8a, 0x7b, 0x28, 0x95, 0x9e, 0x0a, 0x9d, 0x64, 0xd8, 0xd0, 0xd0, 0x03, 0x68, 0x51, 0x41, 0x2e,
	0x38, 0x35, 0x19, 0xb4, 0x71, 0x11, 0x0d, 0x62, 0xe8, 0xcc, 0xb7, 0xa2, 0x1e, 0x34, 0xbe, 0xd1,
	0xcc, 0xe4, 0xde, 0xc1, 0xf9, 0x12, 0x1d, 0xc3, 0xea, 0x8c, 0xf0, 0xd4, 0x9e, 0x5a, 0x9f, 0x3c,
	0x59, 0x2e, 0x1b, 0x4c, 0x83, 0x2c, 0xe0, 0x4c, 0x5c, 0xfa, 0x3a, 0x21, 0x9a, 0x5e, 0x66, 0xd8,
	0x52, 0x76, 0x56, 0x9e, 0x3a, 0xa3, 0x9f, 0x4d, 0xd8, 0xbc, 0xb5, 0x01, 0x9d, 0x41, 0x4b, 0x69,
	0x93, 0x9f, 0x63, 0x94, 0x5e, 0xd6, 0x54, 0x72, 0x7d, 0x43, 0xc1, 0x05, 0x0d, 0x7d, 0x81, 0x76,
	0x48, 0x49, 0xc8, 0x99, 0x28, 0x3d, 0xec, 0xd6, 0x25, 0x1f, 0x14, 0x1c, 0x3c, 0x27, 0xa2, 0x13,
	0x68, 0x92, 0x54, 0xcb, 0x7e, 0xc3, 0x90, 0x5f, 0xd4, 0x25, 0xef, 0xa5, 0x5a, 0x62, 0x43, 0x42,
	0x1f, 0x61, 0x03, 0xd3, 0x80, 0x0a, 0xcd, 0xb3, 0x7d, 0xc2, 0x39, 0x0d, 0xfb, 0x4d, 0xc3, 0xf6,
	0x96, 0x63, 0xcf, 0xdf, 0x22, 0xbe, 0x81, 0x19, 0xb4, 0xa1, 0x65, 0x4b, 0x33, 0xf0, 0xa1, 0x5d,
	0x5a, 0x41, 0x6f, 0xa1, 0x45, 0xbf, 0xc7, 0x2c, 0x29, 0xcb, 0x7e, 0x67, 0x99, 0xe2, 0xf8, 0xc0,
	0x87, 0x66, 0xee, 0x02, 0xbd, 0x87, 0x76, 0x98, 0x26, 0x44, 0x33, 0x29, 0xea, 0x22, 0xe7, 0x80,
	0xbc, 0x3f, 0xba, 0x07, 0x54, 0x69, 0x26, 0x4c, 0xac, 0x16, 0x54, 0xc7, 0xf9, 0x2f, 0xd5, 0xc9,
	0xfb, 0x33, 0x6f, 0x93, 0xbc, 0x3f, 0x1b, 0xe3, 0x0e, 0xb6, 0x01, 0xfa, 0x60, 0x1e, 0xa5, 0x4e,
	0x95, 0xb9, 0xe0, 0x8d, 0xc9, 0xb3, 0xe5, 0x64, 0xaa, 0x29, 0xe7, 0xef, 0x51, 0xa7, 0x0a, 0x17,
	0xa0, 0xd1, 0xd0, 0x5c, 0x83, 0x4e, 0x15, 0x02, 0x68, 0xed, 0xed, 0x9f, 0x1e, 0x9d, 0x4d, 0x7b,
	0xf7, 0xf2, 0xf5, 0xf4, 0xd3, 0xc9, 0x11, 0x9e, 0xf6, 0x9c, 0xd1, 0xaf, 0x26, 0xa0, 0x6b, 0xed,
	0x6c, 0xb7, 0x9f, 0xc3, 0x5a, 0x28, 0x23, 0xc2, 0x84, 0x2a, 0x26, 0xc3, 0xb4, 0xc6, 0x64, 0x30,
	0x28, 0xf7, 0xc0, 0x72, 0xec, 0x78, 0x28, 0xa9, 0x48, 0x40, 0x37, 0xa2, 0x3a, 0x61, 0x81, 0x5f,
	0x5a, 0xce, 0x55, 0xde, 0xd5, 0x56, 0x39, 0xae, 0xc0, 0xac, 0xd4, 0x35, 0x7e, 0x6e, 0x68, 0xc6,
	0x14, 0xd3, 0x32, 0x31, 0x45, 0xff, 0x17, 0x43, 0x67, 0x96, 0x53, 0x18, 0x2a, 0xa8, 0x03, 0x01,
	0xdd, 0xaa, 0xd3, 0x05, 0xd3, 0xed, 0xf0, 0xfa, 0x74, 0x9b, 0xdc, 0xfd, 0x7a, 0x2b, 0x83, 0x6d,
	0xf0, 0x0a, 0x36, 0x6f, 0x79, 0x5e, 0x20, 0xba, 0x55, 0x15, 0xed, 0x54, 0x01, 0x3b, 0xd0, 0xad,
	0x3a, 0xf9, 0xdb, 0xd9, 0x76, 0xe5, 0xec, 0x6b, 0xf7, 0xf3, 0x23, 0x9b, 0x3c, 0x93, 0x9e, 0x59,
	0x78, 0x91, 0x0c, 0x53, 0x4e, 0x95, 0x57, 0x1a, 0xf0, 0x48, 0xcc, 0xbc, 0xd2, 0xc4, 0x45, 0xcb,
	0xfc, 0xe4, 0x1e, 0xff, 0x09, 0x00, 0x00, 0xff, 0xff, 0x39, 0x95, 0xb6, 0xe7, 0xfb, 0x06, 0x00,
	0x00,
}
